# Generated by Django 2.1 on 2019-01-13 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah', models.PositiveIntegerField()),
                ('segments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='recitation',
            name='reciter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation', to='recite.Reciter'),
        ),
        migrations.AddField(
            model_name='recitation',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitation', to='quran.Surah'),
        ),
    ]
